
MAIN_COLOR = "#1E1E21"
ACCENT_COLOR = "#404052"
MAIN_TEXT_COLOR = "#EDEAFF"
FOCUS_MAIN_COLOR = "#385B66"
FOCUS_ACCENT_COLOR = "#567F8D"
FOCUS_TEXT_COLOR = "#F5E5C9"
MAIN_STYLE = f"""
QWidget {{ background-color: {MAIN_COLOR}; color: {MAIN_TEXT_COLOR} }}
"""
