# These can be numbers to save memory, but for debug clarity strings are better
DEVICE_LIST_UPDATE = "DEVICE_LIST_UPDATE"
GET_FILE = "GET_FILE"
SELECT_ITEM = "SELECT_ITEM"
CUSTOM_POPUP = "CUSTOM_POPUP"
PRINT_TO_TEXT_DISPLAY = "PRINT_TO_TEXT_DISPLAY"
ADD_SIDEBAR_STATUS_ENTRY = "ADD_SIDEBAR_STATUS_ENTRY"
