# You may change any of these configurations on your apps startup
JSON_FOLDER = "json"
WINDOWS_SCRIPTS_FOLDER = "windows_scripts"
GET_FILE_AHK_SCRIPT_FILE = "get_currently_selected_file.ahk"
REGISTRY_FILE = "registry.json"
INPUTS_FILE = "inputs.json"
FOLDER_COMMANDS_FILE = "folder_commands.json"
FOLDER_COMMANDS_TEST_COMMANDS_PATH = "test_commands"
FOLDER_COMMANDS_TEST_ENCODERS_PATH = "test_encoders"
AHK = "C:\Program Files\AutoHotkey\AutoHotkey.exe"
